---
- hosts: ws 
  become: yes 
  gather_facts: false
  ignore_errors: True 
  tasks: 
  - name: modify config file
    lineinfile:
       path: /etc/selinux/semanage.conf
       regex: '^module-store ='
       line: module-store = Ayuk is in class
       state: present
