---
- hosts: all
  gather_facts: false
  ignore_errors: True 
  tasks: 
      - name: check uptime
        command: uptime
        register: uptime_output
      - name: disply output 
        debug:
          var: uptime_output.changed
